import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.scss';
import Layout from '../components/Layout';
import Grid from '@material-ui/core/Grid';
import SearchButton from '@material-ui/icons/SearchOutlined';
import TextField from '@material-ui/core/TextField';
// import logoPic from '../public/img/logo.png';


export default function Home() {
  return (
    <>
      {/* <div className={styles.container}> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />
      <div style={{ backgroundColor: '#ffa366', }}>
        <Grid container spacing={3}>
          <Grid item xs={12}>
            <div style={{ textAlign: 'center', fontSize: 27, fontWeight: 'bolder' }}>
              ระบบนามานุกรมข้อมูลภาครัฐ
              <br />
              (Goverment Directory Service)
              <br />
              {/* <Image src={logoPic} alt="Logo" /> */}
              {/* <img src={require('../public/img/logo.png')} /> */}
            </div>
          </Grid>
        </Grid>
        <br />
        <Grid container>
          <Grid item xs={12}>
            <div style={{ textAlign: 'center' }}>

              <TextField placeholder={'Search...'} />
              <button type="submit"><SearchButton /></button>
            </div>
            <br />
          </Grid>
        </Grid>
      </div>

      {/* </div> */}
    </>
  )
}
